### ISSUE TITLE
You've hardcoded get tradelink :v

### ISSUE THREAD

**Issue by DakshMiglani** [CSGORUBY/CSGORUBY.github.io#1]
Change the id to username :V 
https://steamcommunity.com/id/kondaxsolutions/tradeoffers/privacy#trade_offer_access_url

**Comment by Kondax** [comment]
No idea as to why you've opened an issue for this repository.
Also, it's a personal page which means no matter the id supplied you will be redirected to your own: see https://steamcommunity.com/id/test/tradeoffers/privacy#trade_offer_access_url

**Comment by DakshMiglani** [comment]
Yea, I didn't know that. Thanks 👍

**Comment by Stuffa1991** [comment]
oh yes very nice hehehe nice
